// TODO: Put public facing types in this file.

/// Placeholder class — remove once real types are added.
///
/// This stub was generated by the Flutter package template and will be
/// replaced by the actual public API types.
class Awesome {
  /// Always returns `true`.
  bool get isAwesome => true;
}
